version: '3.9'

services:
  app:
    image: node:18
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 3000:3000
    command: bash -c "npm install && npx prisma generate && npm run build && npm run start:prod"
  
  caddy:
    image: caddy/caddy:2.2.1-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
  
volumes:
  caddy_data:
  caddy_config: